# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Beiträge"
  url = "#posts"
  weight = 10

# [[main]]
#   name = "Kurse"
#   url = "courses/"
#   weight = 50


# [[main]]
#   name = "Passwörter"
#   url = "categories/passworter/"
#   weight = 60

# [[main]]
#   name = "test"
#   url = "categories/"
#   weight = 20
#   identifier = "categories"

[[main]]
  name = "Daten sichern"
  url = "categories/"
  weight = 20
  identifier = "daten-sichern"

[[main]]
  name = "Fotos sichern"
  url = "post/fotos-sichern"
  weight = 10
  parent = "daten-sichern"

[[main]]
  name = "Backups"
  url = "post/backups"
  weight = 20
  parent = "daten-sichern"

[[main]]
  name = "Alltags Tips"
  url = "categories/"
  weight = 20
  identifier = "alltags-tips"

[[main]]
  name = "Antiviren Programme"
  url = "post/antiviren-programme"
  weight = 10
  parent = "alltags-tips"

[[main]]
  name = "Werbung im Internet blockieren"
  url = "post/werbung-im-internet-blockieren"
  weight = 20
  parent = "alltags-tips"

[[main]]
  name = "Passwörter"
  url = "categories/"
  weight = 20
  identifier = "Passwörter"

[[main]]
  name = "Sicher Passwörter"
  url = "post/sichere-passwoerter/"
  weight = 10
  parent = "Passwörter"

[[main]]
  name = "Passwort Buch"
  url = "post/passwort-buch"
  weight = 20
  parent = "Passwörter"

[[main]]
  name = "Passwortmanager"
  url = "post/passwortmanager"
  weight = 30
  parent = "Passwörter"

[[main]]
  name = "2 Faktor Authentifizierung"
  url = "post/2-faktor-authentifizierung"
  weight = 40
  parent = "Passwörter"

[[main]]
  name = "Kontakt"
  url = "#contact"
  weight = 50

[[main]]
  name = "Über uns"
  url = "ueber_uns"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
