baseURL = "https://www.technik-tip.de/"
languageCode = "de-de"
title = "Technik-Tip"

[module]
  [[module.imports]]
    # path = "github.com/ajfriesen/hugo-theme-ajfriesen"
    path = "../../hugo-theme-ajfriesen"