baseURL = "https://www.technik-tip.de/"
languageCode = "de-de"
title = "Technik-Tip"
paginate = 1

[module]
  [[module.imports]]
    # path = "github.com/ajfriesen/hugo-theme-ajfriesen"
    path = "../../hugo-theme-ajfriesen"

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"


[params]
  dateFormat = "01.01.2006"
  Author = "Andrej Friesen"

[permalinks]
    page = "/:slug/"